<template>
  <div
    class="chat-log"
    ref="chatLogContainer"
  >
    <message-bubble
      v-for="message in messages"
      :key="message.key"
      :time="message.time"
      :text="message.text"
      :who="message.who"
    ></message-bubble>
    <div
      class="typing-indicator"
      :class="showTypingIndicator ? 'typing-on' : 'typing-off'"
    >
      <div class="lds-ripple">
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
import MessageBubble from '@/components/MessageBubble';
import {EventBus} from '../event-bus.js';

/**
 * Auto scrolls the chat log to the bottom when a new message is received.
 */
function scrollBottom() {
  this.$el.scrollTo(0, this.$el.scrollHeight);
}

export default {
  name: 'chat-log',
  components: {MessageBubble},
  data() {
    return {
      showTypingIndicator: false,
    };
  },
  computed: {
    messages() {
      this.$nextTick(scrollBottom);
      return this.$store.state.chatMessages[this.$store.state.currentChat];
    },
  },
  created() {
    const thisComponent = this;

    // Add a typing indicator visual to the UI
    EventBus.$on('typing-start', (event) => {
      thisComponent.showTypingIndicator = true;
      this.$nextTick(scrollBottom);
    });

    // Remove the typing indicator visual from the UI
    EventBus.$on('typing-stop', (event) => {
      thisComponent.showTypingIndicator = false;
    });

    // Scroll the chat log to the bottom
    this.$nextTick(scrollBottom);
  },
};
</script>

<style scoped>
.chat-log {
  display: block;
  height: inherit;
  width: 100%;
  padding: 2% 4%;
  box-sizing: border-box;
  overflow-y: scroll;
}

.chat-log::-webkit-scrollbar {
  display: none;
}

.typing-indicator {
  display: block;
  width: 36px;
  height: 36px;
/*  width: 100px;
  height: 100px;*/
  margin-bottom: 4px;
  float: left;
  clear: both;
}

.typing-on {
  display: block;
}

.typing-off {
  display: none;
}

/* Loading Ripple Animation */
/* Generated by loading.io */
@keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
@-webkit-keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
.lds-ripple {
  position: relative;
}
.lds-ripple div {
  box-sizing: content-box;
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  -webkit-animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
  animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(1) {
  border-color: #000000;
}
.lds-ripple div:nth-child(2) {
  border-color: rgba(0%,0%,0%,0.675);
  -webkit-animation-delay: -1.3s;
  animation-delay: -1.3s;
}
.lds-ripple {
  width: 36px !important;
  height: 36px !important;
  -webkit-transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
  transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
}
</style>
